###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '3'

services:

  

  hydra:
    image: hedidin/hydra:test
      ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    command:
      serve all --dangerous-force-http
    environment:
#      - LOG_LEVEL=debug
      - OAUTH2_ISSUER_URL=http://654068001HSED.dev-cog.centralus.cloudapp.azure.com:4444
      - OAUTH2_CONSENT_URL=http://654068001HSED.dev-cog.centralus.cloudapp.azure.com:3000/consent
      - OAUTH2_LOGIN_URL=http://654068001HSED.dev-cog.centralus.cloudapp.azure.com:3000/login
#      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
#     Uncomment the following line to use mysql instead.
      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true
      - SYSTEM_SECRET=PureCaca
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=PureCaca
#     - OAUTH2_ACCESS_TOKEN_STRATEGY=jwt
    restart: unless-stopped

  consent:
    environment:
      - HYDRA_URL=http://654068001HSED.dev-cog.centralus.cloudapp.azure.com:4445
    image: oryd/hydra-login-consent-node:v1.0.0-beta.9   
    ports:
      - "3000:3000"
    restart: unless-stopped



#  Uncomment the following section to use mysql instead.
  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
